version: '3'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: leetcode
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data: