version: '3'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: leetcode
    volumes:
      - mongo_data:/data/db
    restart: always

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
    depends_on:
      - mongo
    restart: always

#  server:
#    image: judge0/judge0:latest
#    volumes:
#      - ./judge0.conf:/judge0.conf:ro
#    ports:
#      - "2358:2358"
#    privileged: true
#    restart: always
#
#  worker:
#    image: judge0/judge0:latest
#    command: [ "./scripts/workers" ]
#    volumes:
#      - ./judge0.conf:/judge0.conf:ro
#    privileged: true
#    restart: always
#
#  db:
#    image: postgres:13.0
#    env_file: judge0.conf
#    volumes:
#      - postgres-data:/var/lib/postgresql/data/
#    restart: always
#
#  redis:
#    image: redis:6.0
#    command: [
#      "bash", "-c",
#      'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
#    ]
#    env_file: judge0.conf
#    volumes:
#      - redis-data:/data
#    restart: always

volumes:
  mongo_data:
#  postgres-data:
#  redis-data: